### ISSUE TITLE
Fix spec build issues

### ISSUE THREAD

**Issue by mmocny** [w3c/event-timing#135]
CI is complaining that spec is failing to build due to:
![Screenshot 2023-10-26 at 16 07 57](https://github.com/w3c/event-timing/assets/474282/5ab0f11a-794b-4736-bc86-a2dee41827b1)

Which was added here: https://github.com/w3c/event-timing/commit/7fa8ac5661a16de03415911113aee337f7764049

And indeed does seem like a missing attribute.  Not sure if this was just a warning but it is an error in this repo's CI.

**Comment by clelland** [comment]
I wonder if if just recently became an error in bikeshed?
The attribute looks like it should just be removed, to match the surrounding code. It's already exported as `{{PerformanceEventTIming/interactionId}}`, and that should be maintained.

**Comment by clelland** [comment]
@mmocny, is this still failing? Looks like the latest draft is still from 2022

**Comment by mmocny** [comment]
Fixed via #138
