### ISSUE TITLE
Provide more explanatory material in processing model

### ISSUE THREAD

**Issue by npm1** [w3c/event-timing#51]
From TAG [review](https://github.com/w3ctag/design-reviews/issues/324):

> I'd note that I haven't really dug into the "Processing Model" sections in detail. It seems like it would be useful to have some explanatory material about what those sections do. For example, it seems like this section creates two kinds of timing entries, "firstInput" and "event"; perhaps something should explain in a few sentences which parts of these algorithms create those entries (or change one type to the other) and give them the correct times. Another example of something that might be worth pointing out in prose is that it's possible to get two entries representing the same event (one of each entryType) if an event is both the first input and longer than 104ms. There are probably a bunch of other similar things worth pointing out to readers (including, say, those who are likely to document and teach the specification) that you're aware of but that might not be obvious without very careful consideration of the algorithms in the Processing Model section that might only be done by an implementor.

**Comment by mmocny** [comment]
Closing given the age and the amount of documentation changes made since then.
