### ISSUE TITLE
Alternate semantics for processingStart

### ISSUE THREAD

**Issue by hawkinsw** [w3c/event-timing#55]
I wonder if web application developers might find a use for alternate semantics to the `processingStart` getter:

_always_ return the time when event handlers start to execute

It seems like a web developer may want to know how long it takes the browser to dispatch events to handlers even if there are no handlers registered. The developer could use that information to determine, for example, whether there are certain times that the browser "moves more slowly" than others because of parallel, background operations of the web application.

**Comment by npm1** [comment]
We already do this in Chrome: processingStart is never really 0. It's unclear to me if browser vendors would be interested in dispatching entries for events for which there are no event handlers and for which event handling is optimized out. As such, I'd be ok removing the possibility of returning 0. @tdresser WDYT?

**Comment by tdresser** [comment]
Events with no event handlers can be slow - e.g., slow :hover effects, or slow composited scrolling. We do want to surface these events.

**Comment by npm1** [comment]
Ok, maybe in the future we would be interested in surfacing these events. So then the question is: is it confusing that sometimes 0 is returned instead of a more reasonable value for processingStart? Maybe we should still spec this assuming that the user agent goes through the event dispatching logic?

**Comment by tdresser** [comment]
This is potentially confusing, as these timestamps could be in the middle of a long task.
Maybe that's fine though?

**Comment by npm1** [comment]
Yea it's probably less confusing than exposing 0. It would basically be a very quickly processed event (if you compared startTime and processingStart).

**Comment by tdresser** [comment]
Yup, that SGTM.

The other option would be to use `null`.

**Comment by hawkinsw** [comment]
It sounds like the answer, then, is to take my suggestion and set
processingStart to the time when the event handler would have been
dispatched, even if one were not actually rendered/invoked?

Sorry to have trouble following the back/forth in the messages but
@tdresser's SGTM was a little ambiguous. Thanks for thinking through this
issue with me!

Will

**Comment by npm1** [comment]
Hmm ok, I think I'll change it to be the time at the beginning of the event dispatching logic. If user agents have problems implementing this during implementation then we can consider the alternative solutions (0, null, make up a timestamp).

**Comment by hawkinsw** [comment]
Sounds good. Thanks again for interacting with me on this! I hope that the
feedback is useful. Please let me know if I can be any more helpful!

Will

**Comment by mmocny** [comment]
This has been fixed already.  Now, the only way to not report a processingStart, is to skip reporting the event entirely.
