### ISSUE TITLE
Add element and/or id fields to PerformanceEventTiming to indicate target of the event

### ISSUE THREAD

**Issue by DanShappir** [w3c/event-timing#60]
I propose adding element and/or id fields to PerformanceEventTiming, similar to these fields in LargestContentfulPaint. These fields would indicate the target element of the event that was recorded. Having this information would be very beneficial:
1. It would make it much easier to identify user interactions that have long delays
2. In the context of "first-input", it would help determine which code should be loaded first/preload, based on common visitor interactions
3. Many sites would like to know which elements on the page visitors first interact with, regardless of performance

**Comment by npm1** [comment]
Thanks for the feedback! I agree that this would be useful, and this has been discussed in this issue https://github.com/WICG/event-timing/issues/9. The main question I guess is whether to expose a single EventTarget or the list of all EventTargets (shadow DOM can cause this to be of length >0). Given shadow DOM encapsulation principles, I suspect that people would be opposed to the latter.

**Comment by DanShappir** [comment]
I'm in favor of a single EventTarget

**Comment by npm1** [comment]
Update: we have a concrete plan to add this, which will be a prerequisite for us shipping full Event Timing (for 'discrete' events) in Chrome.

**Comment by clelland** [comment]
Looks like this was shipped in Chrome as `target`; closing this.
