### ISSUE TITLE
It is surprising that 'wheel' event is exluded from the event timing

### ISSUE THREAD

**Issue by smaug----** [w3c/event-timing#89]
Wheel event is possibly the most important input event for many map applications.

**Comment by npm1** [comment]
The reasoning for this is that we haven't thought of a good way to provide developers with a way to normalize these events. Currently we recommend using the number of input events of the type (hence why we have EventCounts). But in the case of wheel events, the number of events dispatched can vary significantly depending on OS and on hardware of the user, so this number cannot be used reliably for normalization. We'd be happy to add it to the list if we can come up with a good normalization story!

**Comment by clelland** [comment]
Closing this, as there has been no response for 3y; if there's still an argument for this, then happy to re-open.
